steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['run', 'init-env-config']
- name: node
  entrypoint: npm
  args: ['test']
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'bash'
  args:
  - -c
  - |
    apt-get install -y zip
    zip -r build.zip build
#artifacts:
#  objects:
#    location: 'gs://iesi-backend-artifacts/$BRANCH_NAME/$BUILD_ID'
#    paths: ['instance.zip', 'core/java/iesi-rest-without-microservices/target/iesi-rest-0.6.0.jar', 'core/java/iesi-rest-without-microservices/target/iesi-rest-0.6.0.jar.original', 'core/java/iesi-core/target/iesi-core-0.6.0.jar']