version: 2
jobs:
  build:
    docker:
    - image: cimg/node:12.20
    steps:
    - checkout
    - run:
        command: |
          if [ ! -f "package.json" ]; then
            echo
            echo "---"
            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
            echo "---"
            echo
            echo "Current directory: $(pwd)"
            echo
            echo
            echo "List directory: "
            echo
            ls
            exit 1
          fi
        name: Checking for package.json.
        working_directory: .
    - restore_cache:
        keys:
        - node-deps-v1-{{ .Branch }}-{{ checksum "./package-lock.json" }}
    - run: 
        command: |
          if [[ ! -z "npm install" ]]; then
            echo "Running override package installation command:"
            npm install
          else
            npm ci
          fi
        name: Installing NPM packages
        working_directory: .

    - run:
        command: npm run init-env-config
        name: Initializing configuration
        working_directory: .

    - run:
        command: npm run test
        name: Run tests

    - run:
        command: CI=false npm run build --url=http://localhost:8080/api
        name: Compile project
        working_directory: .

    - run:
        name: Compress build
        command: |
          cd build
          zip -r iesi-ui-dist-v1.2.1.zip ./*
          mv iesi-ui-dist-v1.2.1.zip ..
          tar -czvf iesi-ui-dist-v1.2.1.tar.gz ./*
          mv iesi-ui-dist-v1.2.1.tar.gz ..

    - store_artifacts:
        path: ./iesi-ui-dist-v1.2.1.zip

    - store_artifacts:
        path: ./iesi-ui-dist-v1.2.1.tar.gz

